[build]
  base = "demo"
  command = "cd ../widget && npm install && npm run build && cd ../demo && npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"

[[headers]]
  for = "/*.db"
  [headers.values]
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=3600, no-transform"
    Content-Type = "application/octet-stream"
    Content-Encoding = "identity"
